title: Boluwatife D. Adeniyi
logo: Bolus.png
description: Experienced Data Analyst with experience working in Research, Finance, and the Public Sector.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
